### ISSUE TITLE
Add generic types for EventEmitter

### ISSUE THREAD

**Issue by endway** [fluix/ng1-shift#105]
Like: `new EventEmitter<OpenEvent>()`.

**Comment by Krakabek** [comment]
How should it work?
E.g. I create `@Output() private onChange = new EventEmitter<ChangeEvent>();`
And when I want to call `this.onChange.emit(notChangeEvent)` it should cause compilation error?

**Comment by endway** [comment]
@Krakabek yep. As well as `subscribe(event: T)`.

**Comment by Krakabek** [comment]
Will do
