### ISSUE TITLE
Add contribution guide

### ISSUE THREAD

**Issue by Krakabek** [fluix/ng1-shift#107]
As opensource lib it should contain guide for newcomers

**Comment by lahirukawijes** [comment]
Hi, I would like to help you with this. Shall I proceed?

**Comment by Krakabek** [comment]
I think it's better to have someone from maintainers team on this one
@endway @arodik what do you think?

**Comment by arodik** [comment]
I think we need to freeze the project at all because we don't have plans to develop and grow ng1-shift, so I'm not expecting any contributions to this repository
We can patch it if we need some fixes/improvements, but I think we don't need to involve external contributors
